import os

# Use the Render URL if available, otherwise default to localhost for local testing
BASE_URL = os.getenv("BACKEND_URL", "http://localhost:8000")

st.set_page_config(
    page_title="Travel Planner Agentic Application",
    page_icon="✈️",
    layout="centered"
)

st.title("Travel Planner Agentic Application")

# Initialize session state for chat history if needed
if "messages" not in st.session_state:
    st.session_state.messages = []

st.header("Hi! How can I help you plan a trip?")

# --- FIX 1: Add a 'key' to the form ---
with st.form(key="travel_form"):
    # --- FIX 2: Place inputs INSIDE the form block ---
    user_input = st.text_input("Let me know where you want to visit:")
    submit_button = st.form_submit_button(label="Plan My Trip")

# --- FIX 3: Logical check after the form is submitted ---
if submit_button and user_input.strip():
    try:
        with st.spinner("The AI is thinking..."):
            # Ensure the key "query" matches your FastAPI Pydantic model
            payload = {"question": user_input} 
            response = requests.post(f"{BASE_URL}/query", json=payload)
            
            if response.status_code == 200:
                answer = response.json().get("answer", "No answer returned. Try again.")
                
                # Display the result
                st.markdown("### AI Travel Agent")
                st.divider()
                st.write(answer)
                st.divider()
                st.info("Note: This plan was generated by AI. Please verify prices and availability.")
            else:
                st.error(f"Backend error: {response.status_code}")
                
    except Exception as e:
        st.error(f"Failed to connect to the server. Is FastAPI running? Error: {e}")